PUT for Driver Availability Controller (Driver Availability)
ucsb-cs156-w24/proj-gauchoride-w24-7pm-4 pull request #31
Opened 2024-02-28 11:42 UTC by notaryaman

closes #12

2024-03-04 07:11 UTC, andrewpengucsb requested changes
Inadequate PR description

https://ucsb-cs156.github.io/topics/pull_requests/

2024-03-08 01:15 UTC, andrewpengucsb requested changes
Also please give admins the ability to create availabilities

2024-03-08 01:15 UTC, andrewpengucsb commented on src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityController.java
> +    public Object deletemenuitem(
Drivers should only be able to delete their own availabilities, and admins should be able to delete anyones

2024-03-08 01:15 UTC, andrewpengucsb commented on src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityController.java
> +    public DriverAvailability updatemenuitem(
Drivers should only be able to update their own, admins should be able to edit anything

2024-03-10 02:20 UTC, andrewpengucsb requested changes

2024-03-10 02:20 UTC, andrewpengucsb commented on src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityController.java
> +    @GetMapping("")
Regular users should not be able to view driver availabilities, could be pontentially harmful

Other than that good to merge, ping me after change

2024-03-12 22:41 UTC, andrewpengucsb requested changes

2024-03-12 22:41 UTC, andrewpengucsb commented on src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityController.java
> +    public Object deletemenuitem(
Drivers are still able to whatever availability, you need to check which role the user has inside the method and based on that determine whether they can delete or not

Please see existing controller https://github.com/ucsb-cs156/proj-gauchoride/blob/main/src/main/java/edu/ucsb/cs156/gauchoride/controllers/RideController.java

2024-03-12 22:41 UTC, andrewpengucsb commented on src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityController.java
> +    public DriverAvailability updatemenuitem(
Same here as delete

2024-03-12 22:41 UTC, andrewpengucsb commented on src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityController.java
> +        return drivall;
Same comment as the get single

2024-03-14 23:19 UTC, andrewpengucsb approved these changes
LGTM

2024-03-14 23:34 UTC, AllenHsm approved these changes
LGTM! Nice job

2024-03-14 23:37 UTC, merged