GET for Driver Availability Controller (Driver Availability)
ucsb-cs156-w24/proj-gauchoride-w24-7pm-4 pull request #33
Opened 2024-02-28 13:43 UTC by notaryaman

closes #11

2024-03-04 07:12 UTC, andrewpengucsb requested changes
Same here, please update description

2024-03-08 01:18 UTC, andrewpengucsb requested changes

2024-03-08 01:18 UTC, andrewpengucsb commented on src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityController.java
> +    @PreAuthorize("hasRole('ROLE_DRIVER')")
Add admins 
Admins can get any
Drivers can only get their own

2024-03-10 02:22 UTC, andrewpengucsb commented
Seems like this PR now has the same changes as #31

2024-03-10 02:24 UTC, notaryaman commented
@andrewpengucsb we will still get points for it though right?

2024-03-14 23:21 UTC, andrewpengucsb commented
Closing because became duplicate of #31

2024-03-14 23:21 UTC, closed without merging